import React from "react";
import styled from "styled-components";

const Container = styled.div`
  margin: 0;
  padding: 0 5%;
`;
const Terms = () => {
  return (
    <>
      <Container>
        <p>
          <strong>
            General Terms
            <br />
          </strong>
          By accessing and placing an order with Bundans, you confirm that you
          are in agreement with and bound by the terms of service contained in
          the Terms &amp; Conditions outlined below. These terms apply to the
          entire website and any email or other type of communication between
          you and Bundans. Under no circumstances shall Bundans team be liable
          for any direct, indirect, special, incidental or consequential
          damages,
          <br />
          including, but not limited to, loss of data or profit, arising out of
          the use, or the inability to use, the materials on this site, even if
          <br />
          Bundans team or an authorized representative has been advised of the
          possibility of such damages. If your use of materials from
          <br />
          this site results in the need for servicing, repair or correction of
          equipment or data, you assume any costs thereof.
          <br />
          Bundans will not be responsible for any outcome that may occur during
          the course of usage of our resources. We reserve the
          <br />
          rights to change prices and revise the resources usage policy in any
          moment.
        </p>
        <p>
          <strong>
            License
            <br />
          </strong>
          Bundans grants you a revocable, non-exclusive, non-transferable,
          limited license to download, install and use the website strictly
          <br />
          in accordance with the terms of this Agreement.
          <br />
          These Terms &amp; Conditions are a contract between you and Bundans
          (referred to in these Terms &amp; Conditions as “Bundans”,
          <br />
          “us”, “we” or “our”), the provider of the Bundans website and the
          services accessible from the Bundans website (which are
          <br />
          collectively referred to in these Terms &amp; Conditions as the
          “Bundans Service”).
          <br />
          You are agreeing to be bound by these Terms &amp; Conditions. If you
          do not agree to these Terms &amp; Conditions, please do not use
          <br />
          the Bundans Service. In these Terms &amp; Conditions, “you” refers
          both to you as an individual and to the entity you represent. If
          <br />
          you violate any of these Terms &amp; Conditions, we reserve the right
          to cancel your account or block access to your account
          <br />
          without notice.
        </p>
        <p>
          <strong>
            Definitions and key terms
            <br />
          </strong>
          To help explain things as clearly as possible in this Terms &amp;
          Conditions, every time any of these terms are referenced, are
          <br />
          strictly defined as:
          <br />● Cookie: small amount of data generated by a website and saved
          by your web browser. It is used to identify your browser,
          <br />
          provide analytics, remember information about you such as your
          language preference or login information.
          <br />● Company: when this policy mentions “Company,” “we,” “us,” or
          “our,” it refers to Manupet Enterprises, 16 Bamgbopa Street
          <br />
          Abule Ijesha Yaba Lagos that is responsible for your information under
          this Terms &amp; Conditions.
          <br />● Country: where Bundans or the owners/founders of Bundans are
          based, in this case is Nigeria
          <br />● Device: any internet connected device such as a phone, tablet,
          computer or any other device that can be used to visit
          <br />
          Bundans and use the services.
          <br />● Service: refers to the service provided by Bundans as
          described in the relative terms (if available) and on this platform.
          <br />● Third-party service: refers to advertisers, contest sponsors,
          promotional and marketing partners, and others who provide
          <br />
          our content or whose products or services we think may interest you.
          <br />● Website: Bundans.”’s” site, which can be accessed via this
          URL: Bundans.com
          <br />● You: a person or entity that is registered with Bundans to use
          the Services.
          <br />
          Restrictions
          <br />
          You agree not to, and you will not permit others to:
          <br />● License, sell, rent, lease, assign, distribute, transmit,
          host, outsource, disclose or otherwise commercially exploit the
          <br />
          website or make the platform available to any third party.
          <br />● Modify, make derivative works of, disassemble, decrypt,
          reverse compile or reverse engineer any part of the website.
          <br />● Remove, alter or obscure any proprietary notice (including any
          notice of copyright or trademark) of Bundans or its affiliates,
          <br />
          partners, suppliers or the licensors of the website.
        </p>
        <p>
          <strong>
            Return and Refund Policy
            <br />
          </strong>
          Thanks for shopping at Bundans. We appreciate the fact that you like
          to buy the stuff we build. We also want to make sure you
          <br />
          have a rewarding experience while you’re exploring, evaluating, and
          purchasing our products.
          <br />
          As with any shopping experience, there are terms and conditions that
          apply to transactions at Bundans. We’ll be as brief as our
          <br />
          attorneys will allow. The main thing to remember is that by placing an
          order or making a purchase at Bundans, you agree to the
          <br />
          terms along with Bundans.”’s” Privacy Policy.
          <br />
          If, for any reason, You are not completely satisfied with any good or
          service that we provide, don’t hesitate to contact us and we
          <br />
          will discuss any of the issues you are going through with our product.
        </p>
        <p>
          <strong>
            Your Suggestions
            <br />
          </strong>
          Any feedback, comments, ideas, improvements or suggestions
          (collectively, “Suggestions”) provided by you to Bundans with
          <br />
          respect to the website shall remain the sole and exclusive property of
          Bundans.
          <br />
          Bundans shall be free to use, copy, modify, publish, or redistribute
          the Suggestions for any purpose and in any way without any
          <br />
          credit or any compensation to you.
        </p>
        <p>
          <strong>
            Your Consent
            <br />
          </strong>
          We’ve updated our Terms &amp; Conditions to provide you with complete
          transparency into what is being set when you visit our site
          <br />
          and how it’s being used. By using our website, registering an account,
          or making a purchase, you hereby consent to our Terms &amp;
          Conditions.
        </p>
        <p>
          <strong>
            Links to Other Websites
            <br />
          </strong>
          This Terms &amp; Conditions applies only to the Services. The Services
          may contain links to other websites not operated or
          <br />
          controlled by Bundans. We are not responsible for the content,
          accuracy or opinions expressed in such websites, and such
          <br />
          websites are not investigated, monitored or checked for accuracy or
          completeness by us. Please remember that when you use
          <br />a link to go from the Services to another website, our Terms
          &amp; Conditions are no longer in effect. Your browsing and
          interaction
          <br />
          on any other website, including those that have a link on our
          platform, is subject to that website’s own rules and policies. Such
          third parties may use their own cookies or other methods to collect
          information about you.
        </p>
        <p>
          <strong>Cookies</strong>
          <br />
          Bundans uses “Cookies” to identify the areas of our website that you
          have visited. A Cookie is a small piece of data stored on
          <br />
          your computer or mobile device by your web browser. We use Cookies to
          enhance the performance and functionality of our website but are
          non-essential to their use. However, without these cookies, certain
          functionality like videos may become unavailable or you would be
          required to enter your login details every time you visit the website
          as we would not be able to
          <br />
          remember that you had logged in previously. Most web browsers can be
          set to disable the use of Cookies. However, if you disable Cookies,
          you may not be able to access functionality on our website correctly
          or at all. We never place Personally Identifiable Information in
          Cookies.
        </p>
        <p>
          <strong>
            Changes To Our Terms &amp; Conditions
            <br />
          </strong>
          You acknowledge and agree that “Bundans” may stop (permanently or
          temporarily) providing the Service (or any features within the
          Service) to you or to users generally at “Bundans'”s sole discretion,
          without prior notice to you. You may stop using the Service at any
          time. You do not need to specifically inform “Bundans” when you stop
          using the Service. You
          <br />
          acknowledge and agree that if “Bundans”disables access to your
          account, you may be prevented from accessing the Service, your account
          details or any files or other materials which is contained in your
          account.
          <br />
          If we decide to change our Terms &amp; Conditions, we will post those
          changes on this page, and/or update the Terms &amp; Conditions
          <br />
          modification date below.
        </p>
        <p>
          <strong>
            Modifications to Our website
            <br />
          </strong>
          Bundans reserves the right to modify, suspend or discontinue,
          temporarily or permanently, the website or any service to which it
          connects, with or without notice and without liability to you.
        </p>
        <p>
          <strong>
            Updates to Our website
            <br />
          </strong>
          Bundans may from time to time provide enhancements or improvements to
          the features/ functionality of the website, which may include patches,
          bug fixes, updates, upgrades and other modifications (“Updates”).
          <br />
          Updates may modify or delete certain features and/or functionalities
          of the website. You agree that Bundans has no obligation to (i)
          provide any Updates, or (ii) continue to provide or enable any
          particular features and/or functionalities of the website to you.
          <br />
          You further agree that all Updates will be (i) deemed to constitute an
          integral part of the website, and (ii) subject to the terms
          <br />
          and conditions of this Agreement.
        </p>
        <p>
          <strong>
            Third-Party Services
            <br />
          </strong>
          We may display, include or make available third-party content
          (including data, information, applications and other products
          services) or provide links to third-party websites or services
          (“Third- Party Services”).
          <br />
          You acknowledge and agree that Bundans shall not be responsible for
          any Third-Party Services, including their accuracy, completeness,
          timeliness, validity, copyright compliance, legality, decency, quality
          or any other aspect thereof. Bundans does not assume and shall not
          have any liability or responsibility to you or any other person or
          entity for any Third-Party Services.
          <br />
          Third-Party Services and links thereto are provided solely as a
          convenience to you and you access and use them entirely at your own
          risk and subject to such third parties’ terms and conditions.
        </p>
        <p>
          <strong>
            Term and Termination
            <br />
          </strong>
          This Agreement shall remain in effect until terminated by you or
          Bundans.
          <br />
          Bundans may, in its sole discretion, at any time and for any or no
          reason, suspend or terminate this Agreement with or without prior
          notice.
          <br />
          This Agreement will terminate immediately, without prior notice from
          Bundans, in the event that you fail to comply with any provision of
          this Agreement. You may also terminate this Agreement by deleting the
          website and all copies thereof from your computer.
          <br />
          Upon termination of this Agreement, you shall cease all use of the
          website and delete all copies of the website from your computer.
          <br />
          Termination of this Agreement will not limit any of Bundans’s rights
          or remedies at law or in equity in case of breach by you (during the
          term of this Agreement) of any of your obligations under the present
          Agreement.
        </p>
        <p>
          <strong>
            Copyright Infringement Notice
            <br />
          </strong>
          If you are a copyright owner or such owner’s agent and believe any
          material on our website constitutes an infringement on your
          <br />
          copyright, please contact us setting forth the following information:
          (a) a physical or electronic signature of the copyright owner
          <br />
          or a person authorized to act on his behalf; (b) identification of the
          material that is claimed to be infringing; (c) your contact
          <br />
          information, including your address, telephone number, and an email;
          (d) a statement by you that you have a good faith belief
          <br />
          that use of the material is not authorized by the copyright owners;
          and (e) the a statement that the information in the notification
          <br />
          is accurate, and, under penalty of perjury you are authorized to act
          on behalf of the owner.
        </p>
        <p>
          <strong>Indemnification</strong>
          <br />
          You agree to indemnify and hold Bundans and its parents, subsidiaries,
          affiliates, officers, employees, agents, partners and
          <br />
          licensors (if any) harmless from any claim or demand, including
          reasonable attorneys’ fees, due to or arising out of your: (a) use
          <br />
          of the website; (b) violation of this Agreement or any law or
          regulation; or (c) violation of any right of a third party.
        </p>
        <p>
          <strong>
            No Warranties
            <br />
          </strong>
          The website is provided to you “AS IS” and “AS AVAILABLE” and with all
          faults and defects without warranty of any kind. To the
          <br />
          maximum extent permitted under applicable law, Bundans, on its own
          behalf and on behalf of its affiliates and its and their
          <br />
          respective licensors and service providers, expressly disclaims all
          warranties, whether express, implied, statutory or otherwise,
          <br />
          with respect to the website, including all implied warranties of
          merchantability, fitness for a particular purpose, title and
          <br />
          non-infringement, and warranties that may arise out of course of
          dealing, course of performance, usage or trade practice.
          <br />
          Without limitation to the foregoing, Bundans provides no warranty or
          undertaking, and makes no representation of any kind that
          <br />
          the website will meet your requirements, achieve any intended results,
          be compatible or work with any other software, , systems
          <br />
          or services, operate without interruption, meet any performance or
          reliability standards or be error free or that any errors or
          <br />
          defects can or will be corrected.
          <br />
          Without limiting the foregoing, neither Bundans nor any Bundans’s
          provider makes any representation or warranty of any kind,
          <br />
          express or implied: (i) as to the operation or availability of the
          website, or the information, content, and materials or products
          <br />
          included thereon; (ii) that the website will be uninterrupted or
          error-free; (iii) as to the accuracy, reliability, or currency of any
          <br />
          information or content provided through the website; or (iv) that the
          website, its servers, the content, or e-mails sent from or on
          <br />
          behalf of Bundans are free of viruses, scripts, trojan horses, worms,
          malware, timebombs or other harmful components.
          <br />
          Some jurisdictions do not allow the exclusion of or limitations on
          implied warranties or the limitations on the applicable statutory
          <br />
          rights of a consumer, so some or all of the above exclusions and
          limitations may not apply to you.
        </p>
        <p>
          <strong>
            Limitation of Liability
            <br />
          </strong>
          Notwithstanding any damages that you might incur, the entire liability
          of Bundans and any of its suppliers under any provision of
          <br />
          this Agreement and your exclusive remedy for all of the foregoing
          shall be limited to the amount actually paid by you for the
          <br />
          website.
          <br />
          To the maximum extent permitted by applicable law, in no event shall
          Bundans or its suppliers be liable for any special,
          <br />
          incidental, indirect, or consequential damages whatsoever (including,
          but not limited to, damages for loss of profits, for loss of
          <br />
          data or other information, for business interruption, for personal
          injury, for loss of privacy arising out of or in any way related to
          <br />
          the use of or inability to use the website, third-party software
          and/or third-party hardware used with the website, or otherwise in
          <br />
          connection with any provision of this Agreement), even if Bundans or
          any supplier has been advised of the possibility of such
          <br />
          damages and even if the remedy fails of its essential purpose.
          <br />
          Some states/jurisdictions do not allow the exclusion or limitation of
          incidental or consequential damages, so the above limitation
          <br />
          or exclusion may not apply to you.
        </p>
        <p>
          <strong>Severability</strong>
          <br />
          If any provision of this Agreement is held to be unenforceable or
          invalid, such provision will be changed and interpreted to
          <br />
          accomplish the objectives of such provision to the greatest extent
          possible under applicable law and the remaining provisions
          <br />
          will continue in full force and effect.
          <br />
          This Agreement, together with the Privacy Policy and any other legal
          notices published by Bundans on the Services, shall
          <br />
          constitute the entire agreement between you and Bundans concerning the
          Services. If any provision of this Agreement is
          <br />
          deemed invalid by a court of competent jurisdiction, the invalidity of
          such provision shall not affect the validity of the remaining
          <br />
          provisions of this Agreement, which shall remain in full force and
          effect. No waiver of any term of this Agreement shall be
          <br />
          deemed a further or continuing waiver of such term or any other term,
          and Bundans.”’s” failure to assert any right or provision
          <br />
          under this Agreement shall not constitute a waiver of such right or
          provision. YOU AND Bundans AGREE THAT ANY CAUSE
          <br />
          OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE
          WITHIN ONE (1) YEAR AFTER THE
          <br />
          CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS
          PERMANENTLY BARRED.
        </p>
        <p>
          <strong>Waiver</strong>
          <br />
          Except as provided herein, the failure to exercise a right or to
          require performance of an obligation under this Agreement shall
          <br />
          not effect a party’s ability to exercise such right or require such
          performance at any time thereafter nor shall be the waiver of a<br />
          breach constitute waiver of any subsequent breach.
          <br />o failure to exercise, and no delay in exercising, on the part
          of either party, any right or any power under this Agreement shall
          <br />
          operate as a waiver of that right or power. Nor shall any single or
          partial exercise of any right or power under this Agreement
          <br />
          preclude further exercise of that or any other right granted herein.
          In the event of a conflict between this Agreement and any
          <br />
          applicable purchase or other terms, the terms of this Agreement shall
          govern.
        </p>
        <p>
          <strong>
            Amendments to this Agreement
            <br />
          </strong>
          Bundans reserves the right, at its sole discretion, to modify or
          replace this Agreement at any time. If a revision is material we will
          <br />
          provide at least 30 days’ notice prior to any new terms taking effect.
          What constitutes a material change will be determined at
          <br />
          our sole discretion.
          <br />
          By continuing to access or use our website after any revisions become
          effective, you agree to be bound by the revised terms. If
          <br />
          you do not agree to the new terms, you are no longer authorized to use
          Bundans.
        </p>
        <p>
          <strong>
            Entire Agreement
            <br />
          </strong>
          The Agreement constitutes the entire agreement between you and Bundans
          regarding your use of the website and supersedes all prior and
          contemporaneous written or oral agreements between you and Bundans.
          <br />
          You may be subject to additional terms and conditions that apply when
          you use or purchase other Bundans’s services, which Bundans will
          provide to you at the time of such use or purchase.
        </p>
        <p>
          <strong>
            Updates to Our Terms
            <br />
          </strong>
          We may change our Service and policies, and we may need to make
          changes to these Terms so that they accurately reflect our
          <br />
          Service and policies. Unless otherwise required by law, we will notify
          you (for example, through our Service) before we make changes to these
          Terms and give you an opportunity to review them before they go into
          effect. Then, if you continue to use the Service, you will be bound by
          the updated Terms. If you do not want to agree to these or any updated
          Terms, you can delete your account.
        </p>
        <p>
          <strong>
            Intellectual Property
            <br />
          </strong>
          The website and its entire contents, features and functionality
          (including but not limited to all information, software, text,
          <br />
          displays, images, video and audio, and the design, selection and
          arrangement thereof), are owned by Bundans, its licensors or
          <br />
          other providers of such material and are protected by Nigeria and
          international copyright, trademark, patent, trade secret and
          <br />
          other intellectual property or proprietary rights laws. The material
          may not be copied, modified, reproduced, downloaded or
          <br />
          distributed in any way, in whole or in part, without the express prior
          written permission of Bundans, unless and except as is
          <br />
          expressly provided in these Terms &amp; Conditions. Any unauthorized
          use of the material is prohibited.
        </p>
        <p>
          <strong>
            Agreement to Arbitrate
            <br />
          </strong>
          This section applies to any dispute EXCEPT IT DOESN’T INCLUDE A
          DISPUTE RELATING TO CLAIMS FOR INJUNCTIVE
          <br />
          OR EQUITABLE RELIEF REGARDING THE ENFORCEMENT OR VALIDITY OF YOUR OR
          Bundans.”’s” INTELLECTUAL
          <br />
          PROPERTY RIGHTS. The term “dispute” means any dispute, action, or
          other controversy between you and Bundans concerning
          <br />
          the Services or this agreement, whether in contract, warranty, tort,
          statute, regulation, ordinance, or any other legal or equitable
          <br />
          basis. “Dispute” will be given the broadest possible meaning allowable
          under law.
        </p>
        <p>
          <strong>
            Notice of Dispute
            <br />
          </strong>
          In the event of a dispute, you or Bundans must give the other a Notice
          of Dispute, which is a written statement that sets forth the
          <br />
          name, address, and contact information of the party giving it, the
          facts giving rise to the dispute, and the relief requested. You
          <br />
          must send any Notice of Dispute via email to: Bundansinc@gmail.com.
          Bundans will send any Notice of Dispute to you by mail to
          <br />
          your address if we have it, or otherwise to your email address. You
          and Bundans will attempt to resolve any dispute through
          <br />
          informal negotiation within sixty (60) days from the date the Notice
          of Dispute is sent. After sixty (60) days, you or Bundans may
          <br />
          commence arbitration.
        </p>
        <p>
          <strong>
            Binding Arbitration
            <br />
          </strong>
          If you and Bundans don’t resolve any dispute by informal negotiation,
          any other effort to resolve the dispute will be conducted
          <br />
          exclusively by binding arbitration as described in this section. You
          are giving up the right to litigate (or participate in as a party or
          <br />
          class member) all disputes in court before a judge or jury. The
          dispute shall be settled by binding arbitration in accordance with
          <br />
          the commercial arbitration rules of the American Arbitration
          Association. Either party may seek any interim or preliminary
          <br />
          injunctive relief from any court of competent jurisdiction, as
          necessary to protect the party’s rights or property pending the
          completion of arbitration. Any and all legal, accounting, and other
          costs, fees, and expenses incurred by the prevailing party shall be
          borne by the non-prevailing party.
        </p>
        <p>
          <strong>
            Submissions and Privacy
            <br />
          </strong>
          In the event that you submit or post any ideas, creative suggestions,
          designs, photographs, information, advertisements, data or
          <br />
          proposals, including ideas for new or improved products, services,
          features, technologies or promotions, you expressly agree
          <br />
          that such submissions will automatically be treated as
          non-confidential and non-proprietary and will become the sole property
          of
          <br />
          Bundans without any compensation or credit to you whatsoever. Bundans
          and its affiliates shall have no obligations with respect
          <br />
          to such submissions or posts and may use the ideas contained in such
          submissions or posts for any purposes in any medium in
          <br />
          perpetuity, including, but not limited to, developing, manufacturing,
          and marketing products and services using such ideas.
        </p>
        <p>
          <strong>Promotions</strong>
          <br />
          Bundans may, from time to time, include contests, promotions,
          sweepstakes, or other activities (“Promotions”) that require you to
          <br />
          submit material or information concerning yourself. Please note that
          all Promotions may be governed by separate rules that may
          <br />
          contain certain eligibility requirements, such as restrictions as to
          age and geographic location. You are responsible to read all
          <br />
          Promotions rules to determine whether or not you are eligible to
          participate. If you enter any Promotion, you agree to abide by
          <br />
          and to comply with all Promotions Rules.
          <br />
          Additional terms and conditions may apply to purchases of goods or
          services on or through the Services, which terms and
          <br />
          conditions are made a part of this Agreement by this reference.
        </p>
        <p>
          <strong>
            Typographical Errors
            <br />
          </strong>
          In the event a product and/or service is listed at an incorrect price
          or with incorrect information due to typographical error, we
          <br />
          shall have the right to refuse or cancel any orders placed for the
          product and/or service listed at the incorrect price. We shall
          <br />
          have the right to refuse or cancel any such order whether or not the
          order has been confirmed and your credit card charged. If
          <br />
          your credit card has already been charged for the purchase and your
          order is canceled, we shall immediately issue a credit to your credit
          card account or other payment account in the amount of the charge.
        </p>
        <p>
          <strong>Miscellaneous</strong>
          <br />
          If for any reason a court of competent jurisdiction finds any
          provision or portion of these Terms &amp; Conditions to be
          <br />
          unenforceable, the remainder of these Terms &amp; Conditions will
          continue in full force and effect. Any waiver of any provision of
          <br />
          these Terms &amp; Conditions will be effective only if in writing and
          signed by an authorized representative of Bundans. Bundans will
          <br />
          be entitled to injunctive or other equitable relief (without the
          obligations of posting any bond or surety) in the event of any breach
          <br />
          or anticipatory breach by you. Bundans operates and controls the
          Bundans Service from its offices in Nigeria. The Service is not
          <br />
          intended for distribution to or use by any person or entity in any
          jurisdiction or country where such distribution or use would be
          <br />
          contrary to law or regulation. Accordingly, those persons who choose
          to access the Bundans Service from other locations do so
          <br />
          on their own initiative and are solely responsible for compliance with
          local laws, if and to the extent local laws are applicable.
          <br />
          These Terms &amp; Conditions (which include and incorporate the
          Bundans Privacy Policy) contains the entire understanding, and
          <br />
          supersedes all prior understandings, between you and Bundans
          concerning its subject matter, and cannot be changed or
          <br />
          modified by you. The section headings used in this Agreement are for
          convenience only and will not be given any legal import.
        </p>
        <p>
          <strong>Disclaimer</strong>
          <br />
          Bundans is not responsible for any content, code or any other
          imprecision.
          <br />
          Bundans does not provide warranties or guarantees.
          <br />
          In no event shall Bundans be liable for any special, direct, indirect,
          consequential, or incidental damages or any damages
          <br />
          whatsoever, whether in an action of contract, negligence or other
          tort, arising out of or in connection with the use of the Service
          <br />
          or the contents of the Service. The Company reserves the right to make
          additions, deletions, or modifications to the contents on
          <br />
          the Service at any time without prior notice. The Bundans Service and
          its contents are provided “as is” and “as available” without any
          warranty or representations of any kind, whether express or implied.
          Bundans is a distributor and not a publisher of the content supplied
          by third parties; as such, Bundans exercises no editorial control over
          such content and makes no warranty or representation as to the
          accuracy, reliability or currency of any information, content, service
          or merchandise provided through or accessible via the Bundans Service.
          Without limiting the foregoing, Bundans specifically disclaims all
          warranties and representations in any content transmitted on or in
          connection with the Bundans Service or on sites that may appear as
          links on the Bundans Service, or in the products provided as
          <br />
          a part of, or otherwise in connection with, the Bundans Service,
          including without limitation any warranties of merchantability,
          <br />
          fitness for a particular purpose or non-infringement of third party
          rights. No oral advice or written information given by Bundans or
          <br />
          any of its affiliates, employees, officers, directors, agents, or the
          like will create a warranty. Price and availability information is
          <br />
          subject to change without notice. Without limiting the foregoing,
          Bundans does not warrant that the Bundans Service will be
          <br />
          uninterrupted, uncorrupted, timely, or error-free.
        </p>
        <p>&nbsp;</p>
      </Container>
    </>
  );
};

export default Terms;
